spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/togedog?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: eric7979!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug

mail:
  address:
    admin: tlsalswns0o@naver.com
jwt:
  key: asdfjkl234890340212345ewsdjksdfajklasdfjkl324jklsdfjklsdfajklaweriopusdfaujioerwjklsdfajkl
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420